version: "3.8"
services:
  lbg-python:
    build: .
    image: lbg-python-app:v1
    environment:
      - PORT=${PORT}
    ports:
      - published: ${PORT}
        target: ${PORT}
        protocol: tcp
    networks:
      - lbg-net
  nginx:
    image: nginx:alpine
    environment:
      - PORT=${PORT}
      - SERVICE=lbg-python
    volumes:
      - type: bind
        source: ./nginx/nginx.conf.template
        target: /etc/nginx/templates/nginx.conf.template
    networks:
      - lbg-net
    ports:
      - published: 80
        target: 80
        protocol: tcp
    depends_on:
      - lbg-python
networks:
  lbg-net:
